"""
Extract LOV data from curated reference files only.

Sources:
  - reference/Attribute Group.xlsx   → Attribute Group ID
  - reference/Brands.xlsx            → Sysco Brand Code, Vendor Brand Code
  - reference/Buyer Group.xlsx       → Item Buyer Group
  - reference/Commodity code.xlsx    → Commodity Code / Taric
  - Hardcoded constants              → Status, Seasonal, Item Group, VAT, Temp,
                                       UOM, allergens, and Customer LOVs
"""

from __future__ import annotations
from typing import Optional
import pandas as pd

# ---------------------------------------------------------------------------
# File-based extractors
# ---------------------------------------------------------------------------


def extract_attribute_groups(path: str) -> pd.DataFrame:
    """
    Attribute Group.xlsx — Row 0: title, Row 1: headers, Row 2+: data
    Columns: Business Centre | Item Group | Attribute Group | STIBO ID
    """
    df = pd.read_excel(path, sheet_name=0, header=None)
    data = df.iloc[2:, [0, 1, 2, 3]].copy()
    data.columns = ["business_centre", "item_group", "attribute_group", "stibo_id"]
    data = data.dropna(subset=["stibo_id"])

    records = []
    for _, row in data.iterrows():
        raw = str(row["stibo_id"]).strip()
        key = str(int(float(raw))).zfill(8) if raw.replace(".", "").isdigit() else raw
        desc = " > ".join(
            str(row[c]).strip()
            for c in ["business_centre", "item_group", "attribute_group"]
            if not pd.isna(row[c]) and str(row[c]).strip()
        )
        records.append(
            {"attribute": "Attribute Group ID", "key": key, "description": desc}
        )

    return pd.DataFrame(records, columns=["attribute", "key", "description"])


def extract_brands(path: str) -> pd.DataFrame:
    """
    Brands.xlsx — Row 0: title, Row 1: headers, Row 2+: data
    Cols 0-1: Sysco Brand Code | Sysco Brand
    Cols 3-4: Vendor Brand Code | Vendor Brand
    """
    df = pd.read_excel(path, sheet_name=0, header=None)
    records = []

    for _, row in df.iloc[2:].iterrows():
        code = row.iloc[0]
        name = row.iloc[1]
        if not pd.isna(code) and str(code).strip():
            records.append(
                {
                    "attribute": "Sysco Brand Code",
                    "key": str(code).strip(),
                    "description": "" if pd.isna(name) else str(name).strip(),
                }
            )

    for _, row in df.iloc[2:].iterrows():
        code = row.iloc[3]
        name = row.iloc[4]
        if not pd.isna(code) and str(code).strip():
            records.append(
                {
                    "attribute": "Vendor Brand Code",
                    "key": str(code).strip(),
                    "description": "" if pd.isna(name) else str(name).strip(),
                }
            )

    return pd.DataFrame(records, columns=["attribute", "key", "description"])


def extract_buyer_groups(path: str) -> pd.DataFrame:
    """
    Buyer Group.xlsx — Row 0: title, Row 1: headers (LE | ID | Description), Row 2+: data
    """
    df = pd.read_excel(path, sheet_name=0, header=None)
    data = df.iloc[2:, [0, 1, 2]].copy()
    data.columns = ["le", "id", "description"]
    data = data.dropna(subset=["id"])

    records = []
    for _, row in data.iterrows():
        key = str(row["id"]).strip()
        le = "" if pd.isna(row["le"]) else str(row["le"]).strip()
        desc = "" if pd.isna(row["description"]) else str(row["description"]).strip()
        label = f"{le} — {desc}" if le else desc
        records.append(
            {"attribute": "Item Buyer Group", "key": key, "description": label}
        )

    return pd.DataFrame(records, columns=["attribute", "key", "description"])


def extract_commodity_codes(path: str) -> pd.DataFrame:
    """
    Commodity code.xlsx — Row 0: title, Row 1: headers (Code | Name), Row 2+: data
    """
    df = pd.read_excel(path, sheet_name=0, header=None)
    data = df.iloc[2:, [0, 1]].copy()
    data.columns = ["code", "name"]
    data = data.dropna(subset=["code"])

    records = []
    for _, row in data.iterrows():
        raw = str(row["code"]).strip()
        key = str(int(float(raw))).zfill(8) if raw.replace(".", "").isdigit() else raw
        desc = "" if pd.isna(row["name"]) else str(row["name"]).strip()
        records.append({"attribute": "Commodity Code", "key": key, "description": desc})

    return pd.DataFrame(records, columns=["attribute", "key", "description"])


# ---------------------------------------------------------------------------
# Hardcoded LOVs (provided explicitly by business)
# ---------------------------------------------------------------------------


def get_hardcoded_lovs() -> pd.DataFrame:
    rows = []

    def add(attribute, key, description=""):
        rows.append({"attribute": attribute, "key": key, "description": description})

    # Status
    for v in ["Active", "Delisted", "Archived"]:
        add("Status", v)

    # Seasonal
    for code, desc in [
        ("01", "Closed for Spring"),
        ("02", "Closed for Summer"),
        ("03", "Closed for Autumn"),
        ("04", "Closed for Winter"),
        ("05", "Closed for Summer, Spring"),
        ("06", "Closed for Autumn, Winter"),
        ("07", "Closed for Autumn, Winter, Spring"),
        ("99", "Non-Seasonal"),
    ]:
        add("Seasonal", code, desc)

    # Item Group
    for code, desc in [
        ("RM-DRY", "Raw Materials - Dry"),
        ("RM-COOLER", "Raw Materials - Cooler"),
        ("RM-FREEZER", "Raw Materials - Freezer"),
        ("FG-DRY", "Finished Goods - Dry"),
        ("FG-COOLER", "Finished Goods - Cooler"),
        ("FG-FREEZER", "Finished Goods - Freezer"),
        ("NON FOOD", "Non Food"),
    ]:
        add("Item Group", code, desc)

    # Item VAT (Purchasing + Selling share same values)
    for code, desc in [
        ("I-STD", "Standard – 20%"),
        ("I-ZERO", "Zero Rated – 0%"),
        ("I-RED", "Reduced – 5%"),
    ]:
        add("Item VAT", code, desc)

    # Temperature
    for code, desc in [
        ("TEMP18", "-18°C (0°F)"),
        ("TEMP0", "0°C (32°F)"),
        ("TEMP5", "5°C (41°F)"),
        ("TEMP8", "8°C (46.4°F)"),
    ]:
        add("Temperature", code, desc)

    # --- Customer LOVs ---

    # Intercompany / Trading Partner
    for code, desc in [
        ("GB01", "Sysco GB (old Brake Bros Ltd)"),
        ("GB57", "Medina Quay Meats Limited"),
        ("GB58", "Fresh Direct UK Ltd"),
        ("GB59", "Kent Frozen Foods"),
        ("GB80", "Sysco Foods NI Limited"),
        ("IE01", "Sysco Foods Ireland UC"),
        ("IE02", "Classic Drinks"),
        ("IE03", "Ready Chef"),
        ("IE90", "SMS Int'l Resources Ireland Unlimited"),
        ("HK91", "SMS GPC International Limited"),
        ("HK92", "SMS GPC International Resources Limited"),
        ("SE99", "Menigo Group"),
        ("SE01", "Menigo Food Service AB"),
        ("SE02", "Fruktservice i Helsingborg AB"),
        ("SE03", "Ekofisk"),
        ("SE04", "Servicestyckarna AB"),
        ("SE05", "Restaurangakademien"),
    ]:
        add("Intercompany/Trading Partner", code, desc)

    # Customer Group
    for code, desc in [
        ("BRAKES", "Brakes"),
        ("COUNTRY_CHOICE", "Country Choice"),
        ("BCE", "BCE"),
        ("KFF", "KFF"),
        ("FRESH_DIRECT", "Fresh Direct"),
        ("MEDINA", "Medina"),
        ("SYSCO_ROI", "Sysco ROI"),
        ("SYSCO_NI", "Sysco NI"),
        ("CLASSIC_DRINKS", "Classic Drinks"),
        ("READY_CHEF", "Ready Chef"),
        ("MENIGO", "Menigo"),
        ("SERVICESTYCKARNA", "Servicestyckarna"),
        ("FRUKTSERVICE", "Fruktservice"),
        ("EKOFISK", "Ekofisk"),
        ("SYSCO_FRANCE", "Sysco France"),
        ("LAG", "LAG"),
    ]:
        add("Customer Group", code, desc)

    # Division
    for code, desc in [
        ("TRS", "Territory Street Accounts"),
        ("TRP", "Territory Program"),
        ("LCC", "Local Contract Customer"),
        ("CMU", "Corporate Multi Unit"),
        ("OTH", "Bid & Other"),
        ("WHL", "Wholesale"),
        ("MIS", "Miscellaneous"),
    ]:
        add("Division", code, desc)

    # Method of Payment
    for code, desc in [
        ("C_DD_BASE", "Direct Debit Business Base Currency"),
        ("C_DD_OTHER", "Direct Debit Foreign Currency"),
        ("C_CASH", "Cash Payment"),
        ("C_CARD", "Debit/Credit Card Payment"),
        ("C_STRDCARD", "Purchase/Stored Card Payment"),
        ("C_BANK", "Direct Payment in Bank"),
        ("C_SWISH", "Swish Payment"),
        ("C_AUTOGIRO", "Autogiro Payment"),
        ("C_CHEQUE", "Cheque Payment"),
        ("C_CONTRA", "Cust/Vend Contra Account"),
        ("V_BACS_BAS", "BACS Business Base Currency"),
        ("V_BACS_OTH", "BACS Foreign Currency"),
        ("V_CASH", "Cash Payment"),
        ("V_CARD", "Credit Card Payment"),
        ("V_SWISH", "Swish Payment"),
        ("V_AUTOGIRO", "Autogiro Payment"),
        ("V_BANK", "Direct Payment in Bank"),
        ("V_CONTRA", "Cust/Vend Contra Account"),
        ("V_DD_BASE", "Direct Debit Business Base Currency"),
        ("V_DD_OTHER", "Direct Debit Foreign Currency"),
        ("V_CHEQUE", "Cheque Payment"),
    ]:
        add("Method of Payment", code, desc)

    # Mode of Delivery
    for code, desc in [
        ("3PL", "Outsourced Transportation and Warehousing"),
        ("AIR", "Goods Delivered by Air"),
        ("AMB_TRK", "Non-Temp Controlled Trucks"),
        ("ANY", "Default Any Vehicle Type"),
        ("BACK_HAUL", "Sysco Fleet Collects from Supplier"),
        ("BICYCLE", "Delivery by Bike"),
        ("BOAT", "Goods Shipped by Sea"),
        ("BULK_CRR", "Large Ships for Bulk Food"),
        ("COLD_STRG", "Temp-Controlled Logistics"),
        ("CONSOL", "Multiple Vendors/Customers, One Transport"),
        ("CONT_SHIP", "Goods Transport via Shipping Containers"),
        ("COURIER", "Small Parcel Deliveries via 3PL"),
        ("CROSS_DOCK", "Goods Moved Internally Before Final Receipt"),
        ("CUST_COLL", "Customers Pick Up at Warehouse"),
        ("DIRECT", "Items Shipped Directly from Supplier"),
        ("DRON_DLV", "Delivered via Drones"),
        ("FROZ_TRK", "Trucks with Freezers for Frozen Items"),
        ("INTERMOD", "Multiple Transport Modes"),
        ("PICKUP", "Collection from Designated Location"),
        ("PIPELINE", "Delivery via Pipelines"),
        ("REFR_TRK", "Temp-Controlled Truck for Perishables"),
        ("TRAIN", "Transport by Rail"),
        ("TRUCK", "Goods Delivered by Road"),
    ]:
        add("Mode of Delivery", code, desc)

    # Individual allergen attributes — key 0/1/2 per allergen column
    _ALLERGENS = [
        "Almonds",
        "Barley",
        "Brazil Nuts",
        "Cashew Nuts",
        "Celery and products thereof",
        "Crustaceans and products thereof",
        "Eggs and products thereof",
        "Fish and products thereof",
        "Gluten at > 20 ppm",
        "Hazelnuts",
        "Kamut",
        "Lupin and products thereof",
        "Macadamia Nuts/Queensland Nuts",
        "Milk and products thereof",
        "Molluscs and products thereof",
        "Mustard and products thereof",
        "Nuts",
        "Oats",
        "Peanuts and products thereof",
        "Pecan Nuts",
        "Pistachio Nuts",
        "Rye",
        "Sesame seeds and products thereof",
        "Soybeans and products thereof",
        "Spelt",
        "Sulphur Dioxide > 10ppm",
        "Walnuts",
        "Wheat",
        # Free-from / certifications
        "Dairy Free",
        "Gluten Free",
        "Halal",
        "Kosher",
        "Vegan",
        "Vegetarian",
        "Organic",
    ]
    _ALLERGEN_LOVS = [
        ("0", "Does Not Contain"),
        ("1", "May Contain"),
        ("2", "Contains"),
    ]
    for allergen in _ALLERGENS:
        for key, desc in _ALLERGEN_LOVS:
            add(allergen, key, desc)

    # Product Source Type
    for code, desc in [
        ("STOCKED", "Stocked"),
        ("JUST_IN_TIME", "Just In Time"),
        ("LEAD_TIME", "Lead Time"),
        ("MAKE_TO_ORDER", "Make to Order"),
    ]:
        add("Product Source Type", code, desc)

    # Ecom Hierarchy Level 2 ID
    for code, desc in [
        ("1000100", "Alcohol > Beer"),
        ("1000110", "Alcohol > Champagne"),
        ("1000120", "Alcohol > Mixers"),
        ("1000130", "Alcohol > Non Alcoholic"),
        ("1000140", "Alcohol > Alcohol Other"),
        ("1000150", "Alcohol > Port"),
        ("1000160", "Alcohol > Red Wine"),
        ("1000170", "Alcohol > Rose Wine"),
        ("1000180", "Alcohol > Spirits"),
        ("1000190", "Alcohol > White Wine"),
        ("1000200", "Alcohol > Wine"),
        ("1000210", "Alcohol > Cooking Wine"),
        ("1100100", "Bakery & Savoury > Bagels"),
        ("1100110", "Bakery & Savoury > Baskets & Nests"),
        ("1100120", "Bakery & Savoury > Biscuits Cookies & Bars"),
        ("1100130", "Bakery & Savoury > Bread"),
        ("1100140", "Bakery & Savoury > Cakes Buns & Cupcakes"),
        ("1100150", "Bakery & Savoury > Bakery & Savoury Confectionery"),
        ("1100160", "Bakery & Savoury > Scones"),
        ("1100170", "Bakery & Savoury > Sliced Square Loaves"),
        ("1100180", "Bakery & Savoury > Speciality Breads"),
        ("1100190", "Bakery & Savoury > Split Tin Loaf"),
        ("1100200", "Bakery & Savoury > Sweet Pastry"),
        ("1100210", "Bakery & Savoury > Viennoiseries"),
        ("1100220", "Bakery & Savoury > Bakery & Savoury Other"),
        ("1100230", "Bakery & Savoury > Pastry"),
        ("1100240", "Bakery & Savoury > Pastry Frozen"),
        ("1100250", "Bakery & Savoury > Pies & Tarts"),
        ("1100260", "Bakery & Savoury > Sandwich & Deli"),
        ("1100270", "Bakery & Savoury > Savoury Canape"),
        ("1100280", "Bakery & Savoury > Scones & Crumpets"),
        ("1100290", "Bakery & Savoury > Cookies Doughnuts & Muffins"),
        ("1100300", "Bakery & Savoury > Crackers"),
        ("1100310", "Bakery & Savoury > Croissants"),
        ("1100320", "Bakery & Savoury > Garlic Bread"),
        ("1100330", "Bakery & Savoury > Gluten Free"),
        ("1100340", "Bakery & Savoury > Individual & Mini Desserts"),
        ("1200100", "Hot & Cold Beverages > Coffee"),
        ("1200110", "Hot & Cold Beverages > Functional Drinks"),
        ("1200120", "Hot & Cold Beverages > Hot Chocolate"),
        ("1200130", "Hot & Cold Beverages > Fruit Juices"),
        ("1200140", "Hot & Cold Beverages > Hot & Cold Beverages Other"),
        ("1200150", "Hot & Cold Beverages > Smoothies"),
        ("1200160", "Hot & Cold Beverages > Soft Drinks"),
        ("1200170", "Hot & Cold Beverages > Syrup"),
        ("1200180", "Hot & Cold Beverages > Tea"),
        ("1200190", "Hot & Cold Beverages > Water"),
        ("1200200", "Hot & Cold Beverages > Hot & Cold Beverages Soft Drinks"),
        ("1300100", "Canned & Dried Foods > Canned Fruit"),
        ("1300110", "Canned & Dried Foods > Canned Tomato"),
        ("1300120", "Canned & Dried Foods > Canned Veg"),
        ("1300130", "Canned & Dried Foods > Cereals"),
        ("1300140", "Canned & Dried Foods > Dried Fruit"),
        ("1300150", "Canned & Dried Foods > Honey"),
        ("1300160", "Canned & Dried Foods > Rice"),
        ("1300170", "Canned & Dried Foods > Spices & Herbs"),
        ("1300180", "Canned & Dried Foods > Sugar"),
        ("1300190", "Canned & Dried Foods > Topping"),
        ("1300200", "Canned & Dried Foods > Vinegar"),
        ("1300210", "Canned & Dried Foods > Jam & Marmalade"),
        ("1300220", "Canned & Dried Foods > Nuts"),
        ("1300230", "Canned & Dried Foods > Oil"),
        ("1300240", "Canned & Dried Foods > Canned & Dried Foods Other"),
        ("1300250", "Canned & Dried Foods > Pasta"),
        ("1300260", "Canned & Dried Foods > Pulses & Seeds"),
        ("1400100", "Cleaning & Hygiene > Cleaning"),
        ("1400110", "Cleaning & Hygiene > Guest Amenities"),
        ("1400120", "Cleaning & Hygiene > Chemical"),
        ("1400130", "Cleaning & Hygiene > Janitorial"),
        ("1400140", "Cleaning & Hygiene > Refuse Sacks"),
        ("1400150", "Cleaning & Hygiene > Dispensers"),
        ("1400160", "Cleaning & Hygiene > Hand Towel"),
        ("1400170", "Cleaning & Hygiene > Toilet Paper"),
        ("1400180", "Cleaning & Hygiene > Centrefeed"),
        ("1500100", "Condiments > Dressing"),
        ("1500110", "Condiments > Ketchup"),
        ("1500120", "Condiments > Mayonnaise"),
        ("1500130", "Condiments > Mustards & Pestos"),
        ("1500140", "Condiments > Condiments Other"),
        ("1500150", "Condiments > Relish & Chutneys"),
        ("1500160", "Condiments > Condiments Sauces"),
        ("1600100", "Confectionery > Bars"),
        ("1600110", "Confectionery > Crisps"),
        ("1600120", "Confectionery > Gum"),
        ("1600130", "Confectionery > Healthier Snacks"),
        ("1600140", "Confectionery > Mints"),
        ("1600150", "Confectionery > Nuts"),
        ("1600160", "Confectionery > Easter"),
        ("1600170", "Confectionery > Confectionery Other"),
        ("1600180", "Confectionery > Popcorn"),
        ("1600190", "Confectionery > Savoury Snacks"),
        ("1600200", "Confectionery > Snacks"),
        ("1600210", "Confectionery > Sweets"),
        ("1600220", "Confectionery > Tortilla"),
        ("1700100", "Cheese Dairy & Eggs > Artisan Cheese"),
        ("1700110", "Cheese Dairy & Eggs > Butter & Spreads"),
        ("1700120", "Cheese Dairy & Eggs > Buttermilk & Sour"),
        ("1700130", "Cheese Dairy & Eggs > Cheese"),
        ("1700140", "Cheese Dairy & Eggs > Cream"),
        ("1700150", "Cheese Dairy & Eggs > Eggs"),
        ("1700160", "Cheese Dairy & Eggs > Food Cupboard"),
        ("1700170", "Cheese Dairy & Eggs > Frozen Foods"),
        ("1700180", "Cheese Dairy & Eggs > Everyday Essentials"),
        ("1700190", "Cheese Dairy & Eggs > Protein"),
        ("1700200", "Cheese Dairy & Eggs > Snacks"),
        ("1700210", "Cheese Dairy & Eggs > Milk"),
        ("1700220", "Cheese Dairy & Eggs > Yoghurt"),
        ("1700230", "Cheese Dairy & Eggs > Cereal"),
        ("1700240", "Cheese Dairy & Eggs > Dairy Milk & Eggs"),
        ("1700250", "Cheese Dairy & Eggs > Home Baking"),
        ("1700260", "Cheese Dairy & Eggs > Health & Wellness"),
        ("1800100", "Deli & Ready Meals > Antipasti"),
        ("1800110", "Deli & Ready Meals > Charcuterie"),
        ("1800120", "Deli & Ready Meals > Cooked Meat"),
        ("1800130", "Deli & Ready Meals > Cooked Poultry"),
        ("1800140", "Deli & Ready Meals > Salads & Fillings"),
        ("1800150", "Deli & Ready Meals > Canape & Finger Food"),
        ("1800160", "Deli & Ready Meals > Hot Deli"),
        ("1800170", "Deli & Ready Meals > Deli & Ready Meals Other"),
        ("1800180", "Deli & Ready Meals > Pate & Terrine"),
        ("1800190", "Deli & Ready Meals > Pizza"),
        ("1800200", "Deli & Ready Meals > Ready Meals"),
        ("1800210", "Deli & Ready Meals > Soups"),
        ("1900100", "Desserts & Cakes > Dessert Sauce"),
        ("1900110", "Desserts & Cakes > Banqueting Slabs"),
        ("1900120", "Desserts & Cakes > Sorbets"),
        ("1900130", "Desserts & Cakes > Tarts & Pies"),
        ("1900140", "Desserts & Cakes > Flavoured Toppings"),
        ("1900150", "Desserts & Cakes > Tray Bakes"),
        ("1900160", "Desserts & Cakes > Ice Cream"),
        ("1900170", "Desserts & Cakes > Mini Desserts"),
        ("1900180", "Desserts & Cakes > Desserts & Cakes Other"),
        ("1900190", "Desserts & Cakes > Petits Fours"),
        ("1900200", "Desserts & Cakes > Portion"),
        ("1900210", "Desserts & Cakes > Quick Service Product"),
        ("1900220", "Desserts & Cakes > Ice Cream Decoration"),
        ("1900230", "Desserts & Cakes > Fresh Cakes"),
        ("1900240", "Desserts & Cakes > Frozen Cakes"),
        ("1900250", "Desserts & Cakes > Yoghurt Frozen"),
        ("1900260", "Desserts & Cakes > Gluten Free Cake"),
        ("1900270", "Desserts & Cakes > Ice Cream Desserts"),
        ("1900280", "Desserts & Cakes > Ice Cream Cones"),
        ("2000100", "Ethnic Foods > Asian Products"),
        ("2000110", "Ethnic Foods > Japanese"),
        ("2000120", "Ethnic Foods > Mexican & Cajun"),
        ("2000130", "Ethnic Foods > Thai"),
        ("2100100", "Fish & Seafood > Delicatessen"),
        ("2100110", "Fish & Seafood > Fresh Fish"),
        ("2100120", "Fish & Seafood > Frozen Fish"),
        ("2100130", "Fish & Seafood > R I F Fish"),
        ("2100140", "Fish & Seafood > Salmon"),
        ("2200100", "Fruit & Veg > Potato"),
        ("2200110", "Fruit & Veg > Frozen Fruit"),
        ("2200120", "Fruit & Veg > Herbs"),
        ("2200130", "Fruit & Veg > Fruit & Veg Other"),
        ("2200140", "Fruit & Veg > Prepared Fruit"),
        ("2200150", "Fruit & Veg > Prepared Veg"),
        ("2200160", "Fruit & Veg > Speciality"),
        ("2200170", "Fruit & Veg > Dried Fruit"),
        ("2200180", "Fruit & Veg > Fresh Fruit"),
        ("2200190", "Fruit & Veg > Fresh Vegetables"),
        ("2200200", "Fruit & Veg > Fries"),
        ("2200210", "Fruit & Veg > Frozen Vegetables"),
        ("2300100", "Health & Organics > Meat Alternatives"),
        ("2300110", "Health & Organics > Protein Powders"),
        ("2300120", "Health & Organics > Soya Milk"),
        ("2400100", "Baking Ingredients > Chocolate"),
        ("2400110", "Baking Ingredients > Denatured Alcohol"),
        ("2400120", "Baking Ingredients > Flour & Yeast"),
        ("2400130", "Baking Ingredients > Herbs"),
        ("2400140", "Baking Ingredients > Dessert Ingredients"),
        ("2400150", "Baking Ingredients > Purees Frozen"),
        ("2400160", "Baking Ingredients > Sugars"),
        ("2400170", "Baking Ingredients > Purees & Fresh Fruit"),
        ("2500100", "Meat & Poultry > Bacon & Rashers"),
        ("2500110", "Meat & Poultry > Beef"),
        ("2500120", "Meat & Poultry > Chicken"),
        ("2500130", "Meat & Poultry > Duck"),
        ("2500140", "Meat & Poultry > Game"),
        ("2500150", "Meat & Poultry > Lamb"),
        ("2500160", "Meat & Poultry > Other Poultry"),
        ("2500170", "Meat & Poultry > Pork"),
        ("2500180", "Meat & Poultry > Puddings"),
        ("2500190", "Meat & Poultry > Sausages"),
        ("2500200", "Meat & Poultry > Turkey"),
        ("2500210", "Meat & Poultry > Veal"),
        ("2600100", "Stocks & Sauces > Bouillon"),
        ("2600110", "Stocks & Sauces > Marinade & Glazes"),
        ("2600120", "Stocks & Sauces > Stocks & Sauces Other"),
        ("2600130", "Stocks & Sauces > Sauces"),
        ("2700100", "Disposables & Food Packaging > Takeaway Boxes & Containers"),
        ("2700110", "Disposables & Food Packaging > Hot Cups & Lids"),
        ("2700120", "Disposables & Food Packaging > Takeaway Bags"),
        ("2700130", "Disposables & Food Packaging > Gloves"),
        ("2700140", "Disposables & Food Packaging > Portion & Deli Pots"),
        ("2700150", "Disposables & Food Packaging > Cling Film Foil & Parchment"),
        ("2700160", "Disposables & Food Packaging > Cold Cups & Lids"),
        ("2700170", "Disposables & Food Packaging > Disposable Cutlery"),
        ("2700180", "Disposables & Food Packaging > Bakery Disposables"),
        ("2700190", "Disposables & Food Packaging > Greaseproof"),
        ("2700200", "Disposables & Food Packaging > Straws"),
        ("2800100", "Kitchen Essentials > Kitchen Equipment"),
        ("2800110", "Kitchen Essentials > Chefwear"),
        ("2800120", "Kitchen Essentials > Gastronorm"),
        ("2800130", "Kitchen Essentials > Kitchen Utensils"),
        ("2800140", "Kitchen Essentials > Labels"),
        ("2800150", "Kitchen Essentials > Food Storage"),
        ("2800160", "Kitchen Essentials > Chefs Knives"),
        ("2800170", "Kitchen Essentials > Pots & Pans"),
        ("2800180", "Kitchen Essentials > Miscellaneous"),
        ("2900100", "Tableware > Crockery"),
        ("2900110", "Tableware > Napkins"),
        ("2900120", "Tableware > Glassware"),
        ("2900130", "Tableware > Cutlery"),
        ("2900140", "Tableware > Tabletop"),
        ("2900150", "Tableware > Barware"),
        ("2900160", "Tableware > Till Roll & Waiter Pads"),
    ]:
        add("Ecom Hierarchy Level 2 ID", code, desc)

    # First & Second Word — approved word pairs (stored as "WORD1 WORD2")
    _fsw_map = {
        "AIR": ("FRESHENER",),
        "ALCOHOL": ("GEL",),
        "ALMOND": ("CHIP", "FLAKED", "FRESH", "GROUND", "ICING", "SLI", "VEGAN", "WHL"),
        "ANISE": ("STAR",),
        "APPLE": (
            "CARAMEL",
            "CRUMBLE",
            "FRESH",
            "GREEN",
            "PACK",
            "RED",
            "SLICES",
            "TREAT",
        ),
        "APRICOT": ("DRIED", "HALF", "PUREE"),
        "APRON": ("COTTON", "PLASTIC"),
        "ARANCINI": ("PEA", "PORCINI"),
        "ARROWROOT": ("GROUND",),
        "ARTICHOKE": ("FRESH", "HEART"),
        "ASPARAGUS": ("FRESH", "FROZEN"),
        "AUBERGINE": ("FRESH",),
        "AVOCADO": ("FRESH",),
        "BABY": ("CHORIZO",),
        "BACON": ("BACK", "BIT", "CHIP", "GREEN", "SLI", "SMOKED", "STRIP", "VEGAN"),
        "BAG": ("BAGUETTE", "BROWN", "FOOD", "PACK", "PAPER", "PLASTIC"),
        "BAGEL": ("MULTISEED", "PLAIN"),
        "BAGUETTE": ("BARRA", "HINGED"),
        "BAKING": ("ADDITIVE", "MIX", "SODA"),
        "BANANA": ("FRESH", "PUREE"),
        "BAR": ("GRANOLA",),
        "BARLEY": ("PEARL",),
        "BASA": ("FILLETS",),
        "BASE": ("BAKER", "BEEF", "CAKE", "CHICKEN"),
        "BASS": ("SEA",),
        "BAY": ("LEAVES",),
        "BBQ": ("CHICKEN", "CHKN"),
        "BEAN": (
            "BAKED",
            "BLACK",
            "BORLOTTI",
            "BURGER",
            "BUTTER",
            "CANNELLINI",
            "CHILI",
            "CURD",
            "GREEN",
            "HARICOT",
            "KIDNEY",
            "LENTIL",
            "RED",
            "ROLL",
            "VANILLA",
            "WHOLE",
        ),
        "BEAR": ("GROUND",),
        "BEEF": (
            "AND",
            "BLADE",
            "BONE",
            "BRISKET",
            "BURGER",
            "CHEEK",
            "CORNED",
            "CUBE",
            "DICED",
            "EYE",
            "FAT",
            "FILLET",
            "FORE-RIB",
            "GROUND",
            "KIDNEY",
            "KNUCKLE",
            "LOIN",
            "MEAT",
            "MINCE",
            "RIB",
            "RIBEYE",
            "ROAST",
            "ROLL",
            "ROUND",
            "RUMP",
            "SALT",
            "SHIN",
            "SILVERSIDE",
            "SLI",
            "SLICED",
            "STEAK",
            "STRIP",
            "TAIL",
            "TOMATO",
            "TONGUE",
            "TOP",
            "TRIM",
            "WHOLE",
        ),
        "BEER": ("GINGER", "IPA"),
        "BEET": ("FRESH", "ROOT"),
        "BERRY": ("DRIED", "FRESH", "WILD"),
        "BIN": ("WASTE",),
        "BISCUIT": ("CHEESE", "MACAROON", "MIX", "TEA"),
        "BLACKBERRY": ("FRESH",),
        "BLEACH": ("LIQUID",),
        "BLUEBERRY": ("BIT",),
        "BOAR": ("BURGER", "GROUND", "WILD"),
        "BOARD": ("WOOD",),
        "BOK": ("CHOY",),
        "BOTTLE": ("GLASS", "SPRAY"),
        "BOWL": ("PAPER",),
        "BOX": ("COOKIE", "FOOD"),
        "BREAD": (
            "BAGUETTE",
            "BROWN",
            "BUN",
            "CHEESE",
            "CIABATTA",
            "CRUMB",
            "ENGLISH",
            "FLAT",
            "FRENCH",
            "GARLIC",
            "GRAIN",
            "LOAF",
            "PITA",
            "PLAIN",
            "ROLL",
            "SLICED",
            "SOURDOUGH",
            "THICK",
            "WHEAT",
            "WHITE",
        ),
        "BREAM": ("SEA", "WHOLE"),
        "BROCCOLI": ("FLORET", "FRESH", "STEM"),
        "BROOM": ("HEAD",),
        "BROTH": ("BEEF", "CHICKEN"),
        "BROWNIE": ("CAKE", "CARAMEL", "CHOC", "CHOCOLATE", "FUDGE"),
        "BRUSH": ("PASTRY",),
        "BULGAR": ("WHEAT",),
        "BUN": (
            "BRIOCHE",
            "BURGER",
            "CHARCOAL",
            "CHOCOLATE",
            "COLA",
            "GLAZED",
            "HIRATA",
            "MINIATURE",
            "ONION",
            "PLAIN",
            "PRETZEL",
            "ROLL",
            "SESAME",
            "WHITE",
        ),
        "BURGER": ("BEEF", "BOX", "VEGAN", "VEGETABLE"),
        "BUTTER": ("BLEND", "BUN", "PATS", "SOLID"),
        "CABBAGE": ("CHINESE", "FRESH", "GREEN", "RED", "SAVOY", "WHITE"),
        "CAKE": (
            "ALMOND",
            "ANGEL",
            "APPLE",
            "CARAMEL",
            "CARROT",
            "CHERRY",
            "CHOC",
            "CHOCOLATE",
            "COFFEE",
            "CREAM",
            "CUSTARD",
            "FRUIT",
            "FUDGE",
            "GATEAU",
            "LEMON",
            "LOAF",
            "MINI",
            "RED",
            "SANDWICH",
            "SHEET",
            "SHORT",
            "SPONGE",
            "STRAWBERRY",
            "TEA",
            "TIRAMISU",
            "TOFFEE",
            "TRAY",
        ),
        "CALZONE": ("CHEESE",),
        "CANDLE": ("SET",),
        "CANDY": (
            "BAR",
            "BEET",
            "CARAMEL",
            "CHERRY",
            "CHOC",
            "CORN",
            "CRACKER",
            "GUMMY",
            "HARD",
            "JELLY",
            "LEMON",
            "LOLLIPOP",
            "LOLLYPOP",
            "MINT",
            "MIX",
            "SPRINKLE",
            "STARBURST",
            "SWEET",
        ),
        "CAP": ("WHITE",),
        "CAPER": ("CAPOTE", "WHOLE"),
        "CAPERS": ("BABY",),
        "CARAMEL": ("MINIATURE", "NUT"),
        "CARRIER": ("PLASTIC",),
        "CARROT": ("APPLE", "BABY", "DICED", "FRESH", "JULIENNE"),
        "CAULIFLOWER": ("FLORET", "FRESH"),
        "CELERY": ("FRESH", "ROOT"),
        "CEREAL": (
            "BAG",
            "BRAN",
            "COCOA",
            "CORN",
            "FROSTED",
            "FRUIT",
            "GRANOLA",
            "INSTANT",
            "MUESLI",
            "RICE",
            "SPECIAL",
        ),
        "CHAISE": ("LOUNGE",),
        "CHARD": ("SWISS",),
        "CHEESE": (
            "BABYBEL",
            "BLACK",
            "BLOCK",
            "BLUE",
            "BRIE",
            "CHEDDAR",
            "CHILI",
            "CLASSIC",
            "COTTAGE",
            "CREAM",
            "CROQUETTE",
            "CUBE",
            "FETA",
            "FOOD",
            "FRENCH",
            "FRIES",
            "FRY",
            "GOAT",
            "GORGONZOLA",
            "GOUDA",
            "GRANA",
            "GREEK",
            "HALLOUMI",
            "ITALIAN",
            "JACK",
            "MEXICAN",
            "MOZZ",
            "ONION",
            "PARMESAN",
            "PIZZA",
            "PORTION",
            "RED",
            "RICOTTA",
            "SLI",
            "SLICES",
            "SMALL",
            "SMOKED",
            "SOFT",
            "SPREAD",
            "STICK",
            "STYLE",
            "SWISS",
            "VEGAN",
            "WEDGE",
            "WHEEL",
        ),
        "CHEESECAKE": (
            "BAILEYS",
            "CAPPUCCINO",
            "CARAMEL",
            "CHERRY",
            "CHOC",
            "CHOCOLATE",
            "LEMON",
            "MIX",
            "NEW",
            "PLAIN",
            "STRAWBERRY",
        ),
        "CHERRY": ("ALMOND", "CHOC", "MARACHINO", "WHOLE"),
        "CHESTNUT": ("PEELED",),
        "CHICKEN": (
            "AND",
            "BONE",
            "BREADED",
            "BREAST",
            "BURGER",
            "CHUNK",
            "CURRY",
            "DICED",
            "DRUMSTICK",
            "FILET",
            "FRIED",
            "HALF",
            "HOT",
            "LEG",
            "MAYONNAISE",
            "MEAT",
            "MIX",
            "NUGGET",
            "QUARTER",
            "SKIN",
            "STRIP",
            "THIGH",
            "WHOLE",
            "WING",
            "WINGS",
        ),
        "CHICKPEA": ("BULK", "CANNED", "DRIED"),
        "CHICORY": ("FRESH",),
        "CHILI": ("CON", "FRESH", "GREEN", "MIX", "PAD", "POWDER", "RED"),
        "CHIP": (
            "BAG",
            "BBQ",
            "CHEESE",
            "CHILI",
            "CHUNK",
            "CORN",
            "CRISP",
            "POTATO",
            "ROLL",
            "TORTILLA",
        ),
        "CHIVE": ("FRESH",),
        "CHOC": ("CHIP", "FONDANT", "LOLLY", "SAUCE"),
        "CHOCLATE": ("DARK", "MILK", "WHITE"),
        "CHOCOLATE": (
            "BAR",
            "BASE",
            "CARAMEL",
            "CHIP",
            "CREAM",
            "CROISSANT",
            "DARK",
            "DROP",
            "FUDGE",
            "MILK",
            "MINT",
            "NUT",
            "ORANGE",
            "ROUALDE",
            "SQUARE",
            "STICK",
            "WHITE",
        ),
        "CHORIZO": ("SLICED",),
        "CHURRO": ("CHOCOLATE", "FILLED"),
        "CHUTNEY": ("APPLE", "FIG", "MANGO", "ONION", "PEAR", "TOMATO"),
        "CIDER": ("APPLE",),
        "CINNAMON": ("GROUND", "STICK"),
        "CITRUS": ("PUNCH",),
        "CLEANER": (
            "BATHROOM",
            "DRAIN",
            "GEL",
            "GRILL",
            "LEMON",
            "LIQUID",
            "MULTI",
            "OVEN",
            "PAD",
            "SPRAY",
            "SUPER",
            "TOILET",
            "VIRABACT",
        ),
        "CLOCK": ("TIME", "WALL"),
        "CLOTH": (
            "ALL",
            "BLUE",
            "CLEANING",
            "GLOVE",
            "GREEN",
            "NET",
            "PAPER",
            "YELLOW",
        ),
        "CLOTHESPIN": ("WOOD",),
        "COCKTAIL": ("APTZR", "SAUCE"),
        "COCOA": ("POWDER",),
        "COCONUT": ("CHOC", "DRIED", "MANGO", "WHL"),
        "COD": (
            "BATTERED",
            "BEER",
            "BITE",
            "BREADED",
            "CUT",
            "FIL",
            "FILET",
            "FILLET",
            "FISH",
            "LOIN",
            "STEAK",
            "TAIL",
        ),
        "COFFEE": (
            "AZERA",
            "BASE",
            "BEANS",
            "BLEND",
            "COOKIE",
            "GROUND",
            "ICED",
            "LITE",
            "MACHINE",
            "NUT",
            "STICK",
            "TEA",
            "TIN",
            "WALNUT",
        ),
        "COLD": ("WATER",),
        "COLORING": ("FOOD",),
        "CONE": ("ICE", "SUGAR", "WAFER", "WAFFLE"),
        "CONTAINER": ("BAGASSE", "FOOD", "SALAD", "SANDWICH"),
        "COOKIE": (
            "BISCUIT",
            "CARAMEL",
            "CHIP",
            "CHOC",
            "CINNAMON",
            "CREAM",
            "CRUMB",
            "FUDGE",
            "JAM",
            "MACAROON",
            "MIX",
            "OATMEAL",
            "SANDWICH",
            "SHORTBREAD",
            "SPREAD",
            "STICK",
        ),
        "COOLER": ("WATER",),
        "CORN": ("BABY", "COB", "FLAKE", "SWEET", "WHL"),
        "COTTON": ("BALL",),
        "COUSCOUS": ("GRAIN", "PEARL"),
        "COVER": ("TABLE",),
        "CRAB": ("CAKE", "MEAT"),
        "CRACKER": ("RICE",),
        "CRANBERRY": ("FRESH",),
        "CRAWFISH": ("TAIL",),
        "CRAYFISH": ("TAIL",),
        "CREAM": (
            "AEROSOL",
            "ALTERNATIVE",
            "BISCUIT",
            "CHEESE",
            "CLEANER",
            "CLOTTED",
            "COCONUT",
            "COFFEE",
            "DOUBLE",
            "FRAICHE",
            "FRESH",
            "LIQUID",
            "PUFF",
            "SET",
            "WHIPPED",
            "WHIPPING",
        ),
        "CREME": ("BRULEE", "CARAMEL", "FRAICHE"),
        "CRISPS": ("HULO",),
        "CROISSANT": ("ALMOND", "BUTTER", "DOUGH", "MINIATURE"),
        "CRUMBLE": ("APPLE",),
        "CRUMPET": ("PLAIN",),
        "CUCUMBER": ("FRESH",),
        "CUP": ("CLEAR", "HALF", "HOT", "PAPER", "PET", "PLASTIC", "WATER", "WHITE"),
        "CURRANT": ("RED",),
        "CURRY": ("PASTE", "POWDER"),
        "CUSTARD": ("CREAM", "MIX"),
        "CUTLERY": ("KIT",),
        "DANISH": ("CINNAMON", "PASTRY", "PECAN"),
        "DATE": ("SLICE",),
        "DEGREASER": ("HEAVY",),
        "DESSERT": (
            "CARAMEL",
            "CUP",
            "FROZEN",
            "MIX",
            "MOUSSE",
            "ORANGE",
            "STRAWBERRY",
            "TIRAMISU",
        ),
        "DETERGENT": ("GLASS", "LIQUID", "MACHINE"),
        "DILL": ("HERB",),
        "DISH": ("PLASTIC",),
        "DISHWASHER": ("LOW",),
        "DISINFECTANT": ("PINE",),
        "DISPENSER": ("BOTTLE", "FILM", "PAPER", "PUMP", "TOWEL"),
        "DOG": ("TREAT",),
        "DOILY": ("PAPER",),
        "DOME": ("LID",),
        "DONUT": (
            "CHOC",
            "CHOUXNUT",
            "CINNAMON",
            "DOUGH",
            "JELLY",
            "MINIATURE",
            "WHITE",
        ),
        "DOUGH": ("BALL", "COOKIE", "MIX"),
        "DOUGHNUT": ("MIX",),
        "DRESSING": ("CAESAR", "FRENCH", "JAPANESE", "YOGURT"),
        "DRIED": ("PEEL",),
        "DRINK": (
            "APPLE",
            "BLACKBERRY",
            "BOT",
            "CANNED",
            "CHERRY",
            "CHOCOLATE",
            "COFFEE",
            "ENERGY",
            "FRUIT",
            "GINGER",
            "GREEN",
            "ITALIAN",
            "LEMON",
            "LEMONADE",
            "MANGO",
            "MIX",
            "ORANGE",
            "PINEAPPLE",
            "RASPBERRY",
            "RED",
            "SMOOTHIE",
            "SPARKLING",
            "STRAWBERRY",
            "SWEET",
            "TROPICAL",
            "WHITE",
        ),
        "DUCK": (
            "BREAST",
            "FAT",
            "GROUND",
            "HALF",
            "LEG",
            "LIVER",
            "MEAT",
            "WHL",
            "WHOLE",
        ),
        "DUST": ("PAN",),
        "DUSTER": ("YELLOW",),
        "EGG": ("LIQUID", "MAYONNAISE", "ROLL", "WHITE", "YOLK"),
        "EMERY": ("BOARD",),
        "EXTRACT": ("VANILLA",),
        "FALAFEL": ("MOROCCAN",),
        "FAT": ("DUCK",),
        "FENNEL": ("FRESH", "SEED"),
        "FIG": ("FRESH",),
        "FILLING": ("CHERRY", "MIX", "PIE", "SANDWICH"),
        "FILM": ("CLING", "FOR", "PVC", "ROLL", "SHRINK"),
        "FILTER": ("COFFEE",),
        "FISH": (
            "BITE",
            "BITES",
            "BTRD",
            "CAKE",
            "FILET",
            "FOOD",
            "PIE",
            "SMOKED",
            "STICK",
            "WHITE",
        ),
        "FLAN": ("CASE",),
        "FLAP": ("JACK",),
        "FLAVOURING": ("ALMOND",),
        "FLOUR": (
            "CORN",
            "MIX",
            "RICE",
            "SELF",
            "SEMOLINA",
            "TORTILLA",
            "WHEAT",
            "WHITE",
            "WRAP",
        ),
        "FLOWER": ("EDIBLE",),
        "FLOWERS": ("FRESH",),
        "FLU": ("MEDIUM",),
        "FOIL": ("FOOD", "ROLL"),
        "FOOD": ("BABY", "FOR", "PET"),
        "FORK": ("WOOD", "WOODEN"),
        "FRENCH": ("FRIES",),
        "FRESH": ("CRESS",),
        "FRESHENER": ("AIR",),
        "FRIES": ("HALLOUMI",),
        "FRITTER": ("CORN",),
        "FRUIT": (
            "BLUEBERRY",
            "COCKTAIL",
            "CRUMB",
            "DRIED",
            "FRESH",
            "FROZEN",
            "MIX",
            "PASTILLES",
            "PINEAPPLE",
            "SCONE",
            "SMOOTHIE",
            "STICK",
        ),
        "FUDGE": ("CHOCOLATE",),
        "GAME": ("MEAT",),
        "GARLIC": (
            "BULB",
            "CHOPPED",
            "CLOVE",
            "FRESH",
            "PEELED",
            "POWDER",
            "PUREE",
            "SALT",
        ),
        "GAS": ("CARBON",),
        "GELATIN": ("GEL",),
        "GINGER": ("BEER", "FRESH", "ROOT"),
        "GLACE": ("LOBSTER",),
        "GLASS": ("JUICE", "PLASTIC", "WATER"),
        "GLASSES": ("READING", "SAFETY"),
        "GLAZE": ("BALSAMIC", "BARBECUE", "BASE", "MIX"),
        "GLOVE": ("NITRILE", "OVEN", "RUBBER", "VINYL"),
        "GRAPE": ("RED", "WHITE"),
        "GRAPEFRUIT": ("FRESH", "RUBY", "SECTION"),
        "GRASS": ("GREEN",),
        "GRAVY": ("BASE", "BEEF", "CHICKEN"),
        "GREEN": ("FRESH", "PEPPERCORNS"),
        "GROUND": ("PAPRIKA",),
        "GUACAMOLE": ("FRESH", "SAUCE"),
        "GUINEA": ("WHL",),
        "GUM": ("BUBBLE", "XANTHAN"),
        "HADDOCK": ("BATTERED", "FILET", "LOIN", "SMOKED", "STICK"),
        "HAGGIS": ("TRADITIONAL",),
        "HAIRNET": ("BLUE",),
        "HAKE": ("FILET",),
        "HALIBUT": ("FILET",),
        "HAM": (
            "BBQ",
            "COOKED",
            "GREEN",
            "HALF",
            "HOCK",
            "HONEY",
            "LEG",
            "PARMA",
            "PIZZA",
            "SLICED",
            "SMOKED",
            "STEAK",
            "WHOLE",
        ),
        "HARNESS": ("HEAD",),
        "HASHBROWN": ("ROUND",),
        "HERB": (
            "BASIL",
            "CHIVE",
            "CRISP",
            "FRESH",
            "LEMON",
            "MINT",
            "MIX",
            "PARSLEY",
            "SAGE",
            "SEED",
            "TARRAGON",
        ),
        "HOLDER": ("CUP",),
        "HONEY": ("CLEAR", "COMB", "FRESH", "LIQUID"),
        "HONEYCOMB": ("WHL", "WHOLE"),
        "HORSERADISH": ("FRESH",),
        "HOT": ("DOG",),
        "HUMMUS": ("ORIGINAL",),
        "ICE": ("CREAM", "CUBE", "DAIRY", "FRUIT", "LOLLY", "MILK", "ORANGE"),
        "ICING": (
            "BANANA",
            "BUN",
            "CARAMEL",
            "CHOC",
            "GLAZE",
            "LEMON",
            "STRAWBERRY",
            "SUGAR",
            "TOFFEE",
        ),
        "IN": ("SYRUP",),
        "JAM": (
            "APRICOT",
            "ASSORTED",
            "BLACKCURRANT",
            "CHERRY",
            "FRUIT",
            "RASPBERRY",
            "SPONGE",
            "STRAWBERRY",
        ),
        "JELLY": ("ORANGE", "QUINCE", "RED", "STRAWBERRY"),
        "JUICE": (
            "APPLE",
            "BERRY",
            "CRANBERRY",
            "DRINK",
            "LEMON",
            "LIME",
            "MANGO",
            "ORANGE",
            "PEAR",
            "PINEAPPLE",
            "TOMATO",
        ),
        "KALE": ("FRESH",),
        "KETCHUP": ("PACKET", "SQUEEZY", "TABLE", "TOMATO"),
        "KIWI": ("FRESH",),
        "KNIFE": ("BONE", "STEAK"),
        "KOHLRABI": ("FRESH",),
        "LABEL": (
            "DAILY",
            "DATE",
            "DAY",
            "MAILER",
            "PAPER",
            "ROLL",
            "SAT",
            "WED",
            "WHITE",
        ),
        "LAMB": (
            "BONE",
            "BREAST",
            "CUT",
            "DICED",
            "GROUND",
            "KIDNEY",
            "LEG",
            "LIVER",
            "LOIN",
            "RACK",
            "ROLL",
            "SHANK",
            "SHOULDER",
            "STEAK",
            "WHL",
            "WHOLE",
        ),
        "LARD": ("BLOCK",),
        "LASAGNA": ("BEEF", "VEG"),
        "LAUNDRY": ("POWDER",),
        "LEAF": ("FRESH",),
        "LEAVES": ("FRESH",),
        "LEEK": ("BABY", "FRESH"),
        "LEG": ("STEAK",),
        "LEMON": ("BLUEBERRY", "CURD", "FRESH", "GLAZE", "ROU"),
        "LEMONADE": ("BOTTLE", "CONCENTRATE", "FRESH", "PINK"),
        "LENTIL": ("GREEN", "PILAF"),
        "LETTUCE": ("FRESH", "ICEBERG", "LOLLO", "RADICCHIO", "RED"),
        "LID": ("BLACK", "BOWL", "CONTAINER", "STOPCOCK", "WHITE"),
        "LIME": ("LEMON", "WEDGE"),
        "LIMEADE": ("CORDIAL",),
        "LINER": ("BIN",),
        "LIQUID": ("DISHWASHER",),
        "LIVER": ("CHICKEN", "DUCK"),
        "LLAMA": ("ROAST",),
        "LNCPS": ("CHIP",),
        "LOBSTER": ("LIVE", "SCAMPI"),
        "MACARONI": ("CHEESE",),
        "MACKEREL": ("FILET",),
        "MANDARIN": ("SEGMENT",),
        "MANGO": ("DICED", "FRESH", "PUREE"),
        "MARGARINE": ("BTR", "TUB"),
        "MARINADE": ("GLAZE",),
        "MARMALADE": ("ONION", "ORANGE", "TUB"),
        "MARSHMALLOW": ("WHITE",),
        "MARZIPAN": ("PREMIUM",),
        "MATZO": ("BALL", "EGG", "MEAL"),
        "MAYONNAISE": (
            "CHIPOTLE",
            "CLASSIC",
            "CORONATION",
            "CUP",
            "GARLIC",
            "LITE",
            "MEXICAN",
            "PACKET",
            "SQUEEZE",
            "VEGAN",
        ),
        "MEAT": ("BALL", "MIX"),
        "MEATBALL": ("VEGAN",),
        "MELON": ("GALIA", "HONEYDEW", "ORANGE"),
        "MERINGUE": ("NEST",),
        "MILK": (
            "ALMOND",
            "BANANA",
            "CARAMEL",
            "CHOC",
            "CHOCOLATE",
            "COCONUT",
            "COFFEE",
            "CONDENSED",
            "EVAPORATED",
            "LIQUID",
            "MINT",
            "OAT",
            "ORGANIC",
            "SEMI",
            "SKIM",
            "SKIMMED",
            "SOY",
            "STRAWBERRY",
            "VANILLA",
            "WHL",
            "WHOLE",
        ),
        "MILKSHAKE": ("BASE",),
        "MINT": ("FRESH", "LOLLY", "SWEET"),
        "MIX": ("BATTER", "GRAVY", "MILK", "MUFFIN", "SMOOTHIE", "SOUP", "STUFFING"),
        "MONKFISH": ("PRTN", "TAIL"),
        "MOP": ("BUCKET", "HANDLE", "HEAD"),
        "MOUSSE": ("CHOC",),
        "MUFFIN": ("BLUEBERRY", "CASE", "CHOC"),
        "MULLET": ("FILET",),
        "MUSHROOM": (
            "BUTTON",
            "CUP",
            "FRESH",
            "OYSTER",
            "PORTOBELLO",
            "SHITAKE",
            "SOUP",
            "STEAK",
            "WILD",
        ),
        "MUSSEL": ("LIVE", "MEAT"),
        "MUSTARD": (
            "BEEF",
            "CHIP",
            "DIJON",
            "ENGLISH",
            "FRENCH",
            "GRAIN",
            "GRAINY",
            "HONEY",
            "PACKET",
            "POWDER",
            "SEED",
            "WHL",
            "YELLOW",
        ),
        "NAPKIN": (
            "1PLY",
            "2PLY",
            "3PLY",
            "CREAM",
            "LINEN",
            "PAPER",
            "SANITARY",
            "WHITE",
        ),
        "NECTARINE": ("FRESH",),
        "NOODLE": ("EGG", "RICE", "UDON"),
        "NUT": (
            "CASHEW",
            "HAZELNUT",
            "MIX",
            "PEANUT",
            "PECAN",
            "PINE",
            "PISTACHIO",
            "PROTEIN",
            "ROAST",
            "WALNUT",
        ),
        "OAT": ("FLAKES", "REGULAR"),
        "OIL": (
            "ALMOND",
            "BUTTER",
            "COOKING",
            "DRUM",
            "GRAPE",
            "OLIVE",
            "SESAME",
            "SUNFLOWER",
            "TRUFFLE",
            "VEGETABLE",
        ),
        "OLIVE": (
            "BLACK",
            "GREEK",
            "GREEN",
            "LEMON",
            "MIX",
            "PITTED",
            "SPANISH",
            "WHOLE",
        ),
        "ONION": (
            "BALL",
            "BALSAMIC",
            "CHIP",
            "CRISP",
            "FRESH",
            "LARGE",
            "MEDIUM",
            "MIX",
            "PICKLE",
            "PICKLED",
            "POWDER",
            "RED",
            "RING",
            "SEED",
            "SLICED",
        ),
        "ORANGE": ("FRESH", "JUICE", "LEMON", "MANDARIN", "SECTION"),
        "ORDER": ("FORM",),
        "PACKET": ("TOILET",),
        "PAD": ("CLEANING",),
        "PAN": ("GRILL",),
        "PANCAKE": ("BASE",),
        "PANCETTA": ("WHOLE",),
        "PANINI": ("PLAIN",),
        "PAPER": ("BAKING", "PARCHMENT", "PRODUCT", "ROLL", "SHEET", "SINGLE"),
        "PARSNIP": ("FRESH",),
        "PARTRIDGE": ("WHOLE",),
        "PASSION": ("FRUIT",),
        "PASTA": (
            "BAULETTI",
            "EGG",
            "FUSILLI",
            "GARGANELLI",
            "GNOCCHI",
            "LASAGNA",
            "LINGUINE",
            "LONG",
            "MACARONI",
            "MIX",
            "ORZO",
            "PENNE",
            "RAVIOLI",
            "SHELL",
            "SPAGHETTI",
            "SPINACH",
            "TAGLIATELLE",
        ),
        "PASTE": ("CHILE", "VANILLA", "WASABI"),
        "PASTRAMI": ("SLICED",),
        "PASTRY": ("BLOCK", "CHOC", "DOUGH", "ECLAIR", "MIX", "RAISIN", "SHELL"),
        "PASTY": ("BEEF", "CHICKEN", "CORNISH"),
        "PATE": ("ARDENNES", "FRESH"),
        "PEA": ("GREEN", "POD", "PUREE", "SNAP"),
        "PEACH": ("FRESH", "HALF", "PUREE", "SLI", "SLICED"),
        "PEANUT": ("BUTTER", "CHILI", "ROASTED", "SALT", "SALTED", "WHOLE"),
        "PEAR": ("FRESH", "HALF", "PUREE"),
        "PEPPER": (
            "BLACK",
            "CHILI",
            "GREEN",
            "HOT",
            "MIXED",
            "PACKET",
            "RED",
            "WHITE",
            "YELLOW",
        ),
        "PEPPERCORN": ("WHOLE",),
        "PEPPERS": ("JALAPENO",),
        "PERMIT": ("WHL",),
        "PHEASANT": ("BREAST",),
        "PICKLE": ("CHIP", "DILL", "GHERKIN", "LARGE", "SLI"),
        "PIE": (
            "APPLE",
            "BAKING",
            "BANOFFEE",
            "BEEF",
            "CHICKEN",
            "FRESH",
            "KEY",
            "LEMON",
            "MINI",
            "MIX",
        ),
        "PIG": ("WHOLE",),
        "PIGEON": ("WHOLE",),
        "PINEAPPLE": ("FRESH", "RING"),
        "PIZZA": (
            "ALL",
            "BASE",
            "BOX",
            "CHICKEN",
            "DOUGH",
            "MINI",
            "PEPPERONI",
            "TOMATO",
        ),
        "PLAICE": ("BREADED", "WHL"),
        "PLANTBASED": ("CHICKEN",),
        "PLASTER": ("PLASTIC",),
        "PLATE": ("GRILL", "LUNCH", "PAPER"),
        "PLUM": ("FRESH", "HALF"),
        "POLISH": ("FURNITURE",),
        "POLLOCK": ("BATTERED", "FILET"),
        "POMEGRANATE": ("FRESH",),
        "POPCORN": ("KERNEL",),
        "PORK": (
            "BACK",
            "BBQ",
            "BELLY",
            "BONE",
            "CHEEK",
            "COLLAR",
            "CUBE",
            "EAR",
            "FAT",
            "FEET",
            "FILET",
            "GROUND",
            "HAM",
            "HEAD",
            "HOCK",
            "KIDNEY",
            "LEEK",
            "LEG",
            "LIVER",
            "LOIN",
            "MEAT",
            "PIE",
            "PUREE",
            "RIB",
            "SHOULDER",
            "SKIN",
            "STEAK",
            "STIR",
            "WHOLE",
        ),
        "POT": ("PIE",),
        "POTATO": (
            "BAKER",
            "BAKING",
            "CHIP",
            "CROQUETTE",
            "CUBE",
            "DICE",
            "DICED",
            "FONDANT",
            "FRESH",
            "FRIES",
            "HASHBROWN",
            "MASH",
            "PUFF",
            "ROAST",
            "ROUND",
            "SKIN",
            "SLI",
            "SWEET",
            "WEDGE",
            "WHITE",
        ),
        "POWDER": ("ARROWROOT", "BAKING", "COCONUT"),
        "PRAWN": ("SHRIMP", "TEMPURA", "WHOLE"),
        "PRESSE": ("ELDERFLOWER",),
        "PRETZEL": ("ROLL", "SOFT"),
        "PRODUCE": ("MISC",),
        "PRODUCT": ("STORAGE",),
        "PRUNE": ("DRIED",),
        "PUDDING": ("BLACK", "MIX"),
        "PUFF": ("PASTRY",),
        "PUMPKIN": ("FRESH", "SEED"),
        "PUREE": ("BERRY", "FRUIT", "PEACH", "PINEAPPLE"),
        "QUAIL": ("WHL",),
        "QUICHE": ("BASE", "CHEESE", "LORRAINE", "MINI", "SHELL", "VEGETABLE"),
        "QUINOA": ("GRAIN",),
        "RABBIT": ("BACON", "WHL"),
        "RADISH": ("FRESH",),
        "RAISIN": ("GOLDEN",),
        "RASPBERRY": ("FRESH", "PUREE"),
        "RED": ("AMARANTH", "GREEN", "LENTIL", "VEIN"),
        "RELISH": ("BURGER", "ONION"),
        "RHUBARB": ("FRESH",),
        "RICE": ("ARBORIO", "BASMATI", "BROWN", "CAKE", "JASMINE", "LONG", "PUREE"),
        "RINSE": ("AID",),
        "ROLL": ("BREAD", "BROWN", "MINI", "RASPBERRY", "ROUND", "RUSTIC", "WHITE"),
        "ROSEMARY": ("FRESH", "HERB"),
        "RUBBER": ("BAND",),
        "RUM": ("RAISIN",),
        "SAGE": ("FRESH",),
        "SALAD": (
            "BEAN",
            "BOWL",
            "CREAM",
            "DRESSING",
            "FROZEN",
            "FRUIT",
            "GARDEN",
            "MIX",
            "SEAWEED",
        ),
        "SALAMI": ("CHORIZO", "SLI"),
        "SALMON": ("FILET", "PACIFIC", "SKIN", "SMOKED", "WHL"),
        "SALSA": ("MEXICAN",),
        "SALT": ("CARAMEL", "FINE", "PACKET", "ROCK", "SEA", "SMOKED", "TABLE", "TUB"),
        "SAMPLE": ("SET",),
        "SANDWICH": ("BACON", "CHICKEN", "FILLING", "WEDGE"),
        "SANITIZER": ("HAND",),
        "SAUCE": (
            "APPLE",
            "BASE",
            "BBQ",
            "BEAN",
            "BOLOGNESE",
            "BRANDY",
            "BROWN",
            "BUTTER",
            "CARAMEL",
            "CHEESE",
            "CHILI",
            "CHIMICHURRI",
            "CHOCOLATE",
            "CRANBERRY",
            "CREAM",
            "CURRY",
            "FISH",
            "GREEN",
            "HABANERO",
            "HORSERADISH",
            "KETCHUP",
            "LOBSTER",
            "MAYONNAISE",
            "MINT",
            "MISO",
            "MIX",
            "MUSHROOM",
            "OYSTER",
            "PACKET",
            "PEPPER",
            "PEPPERCORN",
            "PIZZA",
            "PLUM",
            "RED",
            "SALAD",
            "SALSA",
            "SOY",
            "SWEET",
            "TARTAR",
            "TERIYAKI",
            "TOMATO",
            "WHITE",
            "WORCESTER",
        ),
        "SAUERKRAUT": ("KUHNE",),
        "SAUSAGE": (
            "APPLE",
            "CHORIZO",
            "COCKTAIL",
            "GARLIC",
            "LINK",
            "MEAT",
            "PATTY",
            "PORK",
            "ROLL",
            "STICK",
            "VEGAN",
            "VEGETARIAN",
        ),
        "SCALLOP": ("IQF", "SEA"),
        "SCAMPI": ("WHL",),
        "SCONE": ("APPLE", "CHEESE", "DOUGH", "MIX", "PLAIN"),
        "SEA": ("BURGER", "URCHIN"),
        "SEABASS": ("FILET",),
        "SEAFOOD": ("BASKET", "MIX"),
        "SEASONING": ("CAJUN", "CHIP", "HERB"),
        "SEAWEED": ("NORI",),
        "SEED": ("CHIA", "LIN", "POPPY", "SESAME", "SUNFLOWER", "WHOLE"),
        "SET": ("COLLECTION",),
        "SHAKE": ("BANANA", "BASE", "CHOC", "MIX", "STRAWBERRY", "VANILLA"),
        "SHARPENING": ("STEEL",),
        "SHEET": ("PAN",),
        "SHELL": ("TARTLET",),
        "SHELLOT": ("BANANA",),
        "SHORTBREAD": ("TRAYBAKE",),
        "SHORTCAKE": ("LEMON",),
        "SHRIMP": ("BREADED", "ROLL"),
        "SKEWER": ("BAMBOO", "WOOD"),
        "SLAW": ("DRY",),
        "SLCS": ("BEAN",),
        "SLUSH": ("BASE", "STRAWBERRY"),
        "SMOOTHIE": ("POUCH",),
        "SNACK": ("BAR", "CHIP", "MIX"),
        "SOAP": ("HAND", "LIQUID", "PAD", "POWDER"),
        "SODA": (
            "7-UP",
            "CHERRY",
            "COLA",
            "CRISP",
            "LEMON",
            "LEMONADE",
            "ORANGE",
            "PEPSI",
            "POP",
            "REGULAR",
            "SHANDY",
            "SPRITE",
            "STRAWBERRIES",
        ),
        "SODIUM": ("ALGINATE", "CHL"),
        "SOLE": ("WHOLE",),
        "SORBET": (
            "ACAI",
            "CHAMPAGNE",
            "COCONUT",
            "FRUIT",
            "GELATO",
            "GRAPEFRUIT",
            "LEMON",
            "LIME",
            "MANGO",
            "ORANGE",
            "PEACH",
            "RASPBERRY",
            "STRAWBERRY",
        ),
        "SOUP": ("BROCCOLI", "CHICKEN", "LENTIL", "MUSHROOM", "TOMATO", "VEGETABLE"),
        "SOUR": ("CREAM",),
        "SOYBEAN": ("FRESH",),
        "SPAGHETTI": ("RING",),
        "SPICE": (
            "BASIL",
            "CAJUN",
            "CLOVE",
            "CUMIN",
            "FIVE",
            "GREEN",
            "GROUND",
            "HERB",
            "ITALIAN",
            "JUNIPER",
            "MIX",
            "NUTMEG",
            "POWDER",
            "RUB",
            "SAFFRON",
            "SEED",
            "TARRAGON",
        ),
        "SPINACH": ("BABY", "FRESH"),
        "SPONGE": ("LARGE",),
        "SPOON": ("TEA",),
        "SPRAY": ("HEAD",),
        "SPREAD": ("BUTTER", "CHOCOLATE", "GARLIC", "PORTIONS", "SOFT"),
        "SPRING": ("ROLL",),
        "SPROUT": ("BEAN", "MIX", "SALAD"),
        "SQAUSH": ("APPLE",),
        "SQUASH": ("BUTTERNUT",),
        "SQUID": ("CAL", "STRIP"),
        "STEAK": (
            "BEEF",
            "BONE",
            "CUT",
            "FILET",
            "MINUTE",
            "PIE",
            "RIBEYE",
            "RND",
            "RUMP",
            "SIRLOIN",
            "SLICED",
            "STEW",
            "TOMAHAWK",
        ),
        "STEEL": ("WOOL",),
        "STOCK": ("BASE", "BEEF", "CHICKEN", "FISH", "MIX", "RED", "VEGETABLE"),
        "STOPCOCK": ("MALE", "MET", "ONE", "PLASTIC"),
        "STRAW": ("PAPER",),
        "STRAWBERRY": (
            "BERRY",
            "DAIRY",
            "FRESH",
            "IQF",
            "LOLLY",
            "PUREE",
            "SPLIT",
            "WHL",
        ),
        "STUFFING": ("MIX",),
        "SUET": ("SHREDDED",),
        "SUGAR": (
            "BROWN",
            "CANE",
            "CASTER",
            "CUBE",
            "DARK",
            "DONUT",
            "GRANULATED",
            "LIGHT",
            "PACKET",
            "STICK",
            "SUBSTITUTE",
        ),
        "SWEDE": ("FRESH",),
        "SWEET": ("CHILI",),
        "SWORDFISH": ("LOIN",),
        "SYRUP": (
            "AMARETTO",
            "BANANA",
            "BASE",
            "BLACKBERRY",
            "BLUE",
            "BUTTERSCOTCH",
            "CARAMEL",
            "CHOCOLATE",
            "CINNAMON",
            "COCONUT",
            "GINGER",
            "GINGERBREAD",
            "GOLDEN",
            "GRENADINE",
            "HAZELNUT",
            "HONEY",
            "KIWI",
            "LEMON",
            "LIGHT",
            "MANGO",
            "MAPLE",
            "MINT",
            "MIX",
            "ORANGE",
            "PASSION",
            "PINEAPPLE",
            "PUMPKIN",
            "SALTED",
            "SPECIAL",
            "STRAWBERRY",
            "VANILLA",
        ),
        "TAHINI": ("PASTE",),
        "TAPIOCA": ("PEARLS",),
        "TART": (
            "ALMOND",
            "APPLE",
            "APRICOT",
            "CARAMEL",
            "CHERRY",
            "CHOCOLATE",
            "LEMON",
            "PECAN",
            "SHELL",
        ),
        "TARTLET": ("APPLE",),
        "TEA": (
            "BAG",
            "CHAI",
            "CREAM",
            "ENGLISH",
            "GREEN",
            "LEMON",
            "LIQUID",
            "MINT",
            "PEACH",
            "RASPBERRY",
            "TOWEL",
        ),
        "TEST": ("STRIP",),
        "THICKENER": ("FOOD",),
        "THYME": ("FRESH", "HERB"),
        "TIN": ("FRUIT",),
        "TOAST": ("SESAME",),
        "TOFFEE": ("BUN", "ICING"),
        "TOFU": ("SILKEN",),
        "TOILET": ("PAPER", "ROLL"),
        "TOMATO": (
            "BABY",
            "CHERRY",
            "CHOPPED",
            "DRIED",
            "FRESH",
            "PASTE",
            "PLUM",
            "PUREE",
            "ROUND",
            "SUNDRIED",
            "VINE",
        ),
        "TOPPING": ("SAUCE",),
        "TORTE": ("CHOCOLATE",),
        "TORTILLA": ("CORN",),
        "TOWEL": ("HAND", "PAPER"),
        "TRAY": ("BAKE", "CHIP", "PAPER"),
        "TRAYBACK": ("BAKEWELL",),
        "TRAYBAKE": ("ALMOND", "APPLE", "APRICOT", "BAKEWELL", "FLAPJACK"),
        "TROUT": ("FILET", "SKIN", "SMOKED", "WHL"),
        "TUNA": ("CHUNK", "SALAD", "STEAK"),
        "TURKEY": ("BREAST", "CUTLET", "DICED", "MEAT", "ROLL", "THIGH", "WHL"),
        "TURNIP": ("FRESH",),
        "URINAL": ("SCREEN",),
        "VAC": ("PACK",),
        "VEAL": ("BONE", "CHEEK", "CUTLET", "JUS", "LIVER", "SWEET", "TOP"),
        "VEGAN": ("MEAT",),
        "VEGETABLE": (
            "ASSORTED",
            "BASE",
            "BEEF",
            "JELLY",
            "MIX",
            "NUGGET",
            "PASTE",
            "ROLL",
            "SAMOSA",
            "SAUSAGE",
            "STEW",
        ),
        "VENISON": ("DICED", "GROUND", "LEG", "LOIN", "SADDLE", "STRIP", "TRIMMING"),
        "VINEGAR": (
            "BALSAMIC",
            "CIDER",
            "DISTILLED",
            "MALT",
            "PACKET",
            "RED",
            "RICE",
            "SHERRY",
            "SUSHI",
            "WHITE",
            "WINE",
        ),
        "WAFER": ("BISCUIT", "CHOC", "DISC", "FAN", "PAPER"),
        "WAFFLE": ("BOWL", "CHOC", "CINNAMON", "MIX", "PLAIN"),
        "WATER": (
            "CANNED",
            "ICE",
            "MELON",
            "ORANGE",
            "SODA",
            "SPARKLING",
            "SPRING",
            "STILL",
        ),
        "WATERCRESS": ("FRESH",),
        "WET": ("NAP",),
        "WHITE": ("BAIT",),
        "WHOLE": ("SHEEPHEAD",),
        "WINE": ("COOKING", "PORT", "RED", "WHITE"),
        "WIPE": ("STERILE",),
        "WONTON": ("CHICKEN", "SHRIMP"),
        "WOODEN": ("SPOON",),
        "WRAP": ("FILM", "FOIL", "PALLET"),
        "YEAST": ("DRY",),
        "YOGURT": (
            "ASSORTED",
            "CHERRY",
            "COCONUT",
            "CREAM",
            "FROZEN",
            "FRUIT",
            "GREEK",
            "HONEY",
            "LIME",
            "MIX",
            "NATURAL",
            "PLAIN",
            "VANILLA",
        ),
    }
    for first, seconds in _fsw_map.items():
        for second in seconds:
            add("First & Second Word", f"{first} {second}", f"{first} > {second}")

    # Cost Centre
    for code, desc in [
        ("W10025", "Warehouse"),
        ("W10075", "Certain Item - Whse"),
        ("T15005", "Transportation"),
        ("T15015", "Certain Items - Delv"),
        ("N20015", "Maintenance Occupancy"),
        ("N20005", "Maintenance Fleet"),
        ("N20020", "Maintenance Equipment"),
        ("N20050", "Certain Items - Maint"),
        ("P50890", "Production"),
        ("E55999", "Business Technology"),
        ("E55074", "Certain Items - BT"),
        ("A30899", "Administration"),
        ("R45831", "Merchandising"),
        ("F35005", "Finance"),
        ("I65005", "Strategic Initiatives"),
        ("H40005", "Human Resources"),
        ("C70999", "Supply Chain"),
        ("X75005", "Executive"),
        ("A30099", "Certain Items - G&A"),
        ("S25070", "Sales Shrink"),
        ("S25845", "Selling exp - LCC/CMU"),
        ("S25846", "Selling exp - BID & Other"),
        ("S25847", "Selling exp - Territory"),
        ("S25849", "Selling exp - Customer Serv"),
        ("S25850", "Selling exp - Marketing"),
        ("S25855", "Selling exp - Business Dev"),
        ("S25999", "Sales Default"),
        ("S25305", "Certain Items - Sales"),
    ]:
        add("Cost Centre", code, desc)

    # Delivery Terms (Incoterms)
    for code, desc in [
        ("CFR", "Cost & Freight (C&F)"),
        ("CIF", "Cost, Insurance & Freight"),
        ("CIP", "Carriage & Insurance Paid"),
        ("CPT", "Carriage Paid To"),
        ("DAP", "Delivered At Place"),
        ("DDP", "Delivered Duty Paid"),
        ("DPU", "Delivered At Place Unloaded"),
        ("EXW", "Ex Works"),
        ("FAS", "Free Alongside Ship"),
        ("FCA", "Free Carrier"),
        ("FOB", "Free On Board"),
    ]:
        add("Delivery Terms", code, desc)

    return pd.DataFrame(rows, columns=["attribute", "key", "description"])


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from pathlib import Path

    root = Path(__file__).resolve().parent.parent.parent
    ref = root / "reference"

    dfs = []

    for fname, extractor in [
        ("Attribute Group.xlsx", extract_attribute_groups),
        ("Brands.xlsx", extract_brands),
        ("Buyer Group.xlsx", extract_buyer_groups),
        ("Commodity code.xlsx", extract_commodity_codes),
    ]:
        p = ref / fname
        if p.exists():
            df = extractor(str(p))
            print(f"Loaded {len(df):>6} rows from {fname}")
            dfs.append(df)
        else:
            print(f"Warning: {fname} not found at {p}")

    hardcoded = get_hardcoded_lovs()
    print(f"Loaded {len(hardcoded):>6} rows from hardcoded LOVs")
    dfs.append(hardcoded)

    if not dfs:
        raise SystemExit("No reference files found — nothing to write.")

    flat_df = pd.concat(dfs, ignore_index=True)
    output_path = ref / "lovs_flat.csv"
    flat_df.to_csv(output_path, index=False)
    print(f"\nWrote {len(flat_df)} total LOV rows to {output_path}")
    print(f"Attributes: {sorted(flat_df['attribute'].unique())}")
